version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g serverless@3.38.0
  pre_build:
    commands:
      - echo Compiling TypeScript files...
      - npm run build
  build:
    commands:
      - echo Deploying the application to AWS using Serverless Framework...
      - serverless deploy --region ap-south-1 --verbose
      - ls -lrt
      #- serverless deploy --debug
  post_build:
    commands:
      - echo Build completed successfully!
